# 测试访问外部registry
# 下面变量可在gitlab项目的变量功能中定义，方便脚本使用
#
# CUSTOM_CI_REGISTRY='registry.example.com:10043'
# CUSTOM_CI_REGISTRY_IMAGE='registry.example.com:10043/root/docker'
# CUSTOM_CI_REGISTRY_PASSWORD='secret'
# CUSTOM_CI_REGISTRY_USER='gitlab-ci-token'

image: docker:git

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DB: docker build --pull --no-cache --force-rm=true

services:
 - name: docker:dind
   command: ["--registry-mirror=https://registry.docker-cn.com",
             "--insecure-registry=https://gitlab.example.com:4567",
             "--insecure-registry=https://registry.example.com:10043"]

before_script:
 - whoami
 - pwd
 - docker info
 - echo CI_REGISTRY $CI_REGISTRY
 - docker login -u $CUSTOM_CI_REGISTRY_USER -p $CUSTOM_CI_REGISTRY_PASSWORD $CUSTOM_CI_REGISTRY

stages:
 - build

build-master:
 stage: build
 script:
  - $DB -t $CI_REGISTRY_IMAGE .
  - git config user.email $GITHUB_EMAIL
  - git config user.name $GITHUB_USER
  - git push https://$GITHUB_USER:$GITHUB_TOKEN@github.com/$GITHUB_USER/$CI_PROJECT_NAME.git HEAD:master --force
 only:
  - master

build:
  stage: build
  script:
   - cd services/ssh-container
   - $DB -t $CUSTOM_CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG -t $CUSTOM_CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
   - docker push $CUSTOM_CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
   - docker push $CUSTOM_CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  except:
   - master
  tags:
   - docker
