image: docker:git

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DB: docker build --pull --no-cache --force-rm=true

services:
 - name: docker:dind
   command: ["--registry-mirror=https://registry.docker-cn.com",
             "--insecure-registry=https://gitlab.example.com:4567"]

before_script:
 - docker info
 - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stages:
 - build

build-master:
 stage: build
 script:
  - $DB -t $CI_REGISTRY_IMAGE .
  - git config user.email $GITHUB_EMAIL
  - git config user.name $GITHUB_USER
  - git push https://$GITHUB_USER:$GITHUB_TOKEN@github.com/$GITHUB_USER/$CI_PROJECT_NAME.git HEAD:master --force
 only:
  - master

build:
  stage: build
  script:
   - cd services/ssh-container
   - $DB -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
   - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  except:
   - master
  tags:
   - docker
